spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    import:
      configserver:http://localhost:8888
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      uri:
        - http://localhost:8888
      username: spring_cloud_user
      password: ENC(szIEI5hqs1jeINFFpaaPzJ8wDUF5+hiVzuW6i56nzAkVqQ2L+SOMgsr+tCR/b0Fk)

jasypt:
  encryptor:
    password: password!!

#spring:
#  cloud:
#    config:
#      uri:
#        - http://localhost:8888



