server:
  port: 8888
logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          #uri: file://F:\SpringBoot_Learning\Event-DrivenArchitecure\Event-driven-Service\Microservice-Demo\config-server-repository\
          uri: https://github.com/deeh3kr/event-driven-service-config
          default-label: master
          username: deeh3kr
          password: ENC(Vur8mXRN1MLbI0NI1d02Xo73JthD3MTeNkn/tWVN3pTTwTVTXYO2CECWRS8pCSmQBKcawYlRQTA29FBp2w5AClsGGmWjRgawIidrOdp9qUk=)
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: ENC(snKcVTLSbkzlznRpHl2If4OzhP/ikMqzHGIDfcdT8BVAAFLliKGU9RnvGUuCtDoK)