server:
  port: 8888
logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          #uri: file://F:\SpringBoot_Learning\Event-DrivenArchitecure\Event-driven-Service\Microservice-Demo\config-server-repository\
          uri: https://github.com/deeh3kr/event-driven-service-config
          default-label: master
          username: deeh3kr
          password: '{cipher}c6880a5b47af9710bd3e9830bddb64217544c1f45d1b6a8da8cf3b1ca21e644e6d11b9dd80e435208709093eb7339ae15ab31beb8c9dfe5a67d15e7baaad2fe5'
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '{cipher}7f6d53c3244f96cef96677681ce23288fa8f979942a9066ef177f29031d2c49d86c76791b2df3dd2f3e10540b9ab6ef4'
