version: '3.8'

networks:
  application:
    driver: bridge

services:
  postgres:
    container_name: keycloak_postgres
    image: postgres:${POSTGRES_VERSION:-latest}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # all changes in database will be stored in this volume
      - ./postgres_init/01-init.sh:/docker-entrypoint-initdb.d/init-db.sh # used only on first time container is being built to create database and users
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "KEYCLOAK_DB=keycloak"
      - "KEYCLOAK_DB_USER=keycloak"
      - "KEYCLOAK_DB_PASSWORD=keycloak"
      - "KEYCLOAK_DB_SCHEMA=keycloak"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "postgres", "-U", "postgres" ]
      timeout: 5s
      interval: 10s
      retries: 10
    restart: "no"
    networks:
      - ${GLOBAL_NETWORK:-postgres}
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M